const passageDrafts = [
  "A calm morning gives the mind room to notice useful details. At 7:30, the kitchen was quiet except for the kettle and the soft click of a notebook opening. I wrote three priorities, ignored the rest, and discovered that a smaller plan created more energy than a heroic one. The first task was not exciting, but it had a clear finish line. Once it was complete, the next decision felt lighter. This is the quiet advantage of practice: progress does not always arrive as a dramatic breakthrough. Sometimes it appears as a cleaner desk, a shorter list, or one careful sentence that finally says exactly what you mean.",
  "The old railway station had become a community workshop, although the clock above platform 2 still showed the wrong time. On Saturdays, neighbors carried chairs through the blue doors and arranged them beneath bright paper signs. Someone taught basic repairs; someone else brought soup. Children asked surprisingly precise questions about wheels, wires, and wood. By afternoon, the room sounded like a small, cheerful machine. Nothing was rushed, yet useful things kept getting finished. The organizers learned that a welcoming space does not need expensive equipment. It needs a clear purpose, patient guidance, and enough room for people to try, fail, laugh, and try again.",
  "When a team begins a difficult project, the first challenge is rarely the work itself. It is agreeing on what the work should accomplish. During one planning session, the group wrote every assumption on a whiteboard, including the uncomfortable ones. Which users were they serving? What could wait until version 2? Where would a mistake be expensive? The questions took an hour, but they prevented weeks of confusion. Good planning is not a promise that everything will go smoothly. It is a shared map for the moments when the route becomes uncertain, the schedule changes, or a confident idea meets an inconvenient fact.",
  "A garden teaches patience in a language that requires no translation. Seeds remain invisible for days, and then a green curve appears where the soil looked empty. The gardener cannot command the weather, but can prepare the ground, remove weeds, and provide water at the right time. That balance is useful beyond a garden. We can control the care we bring to a habit, even when the result arrives slowly. In spring, the smallest leaves seem fragile; by August, they create shade for the bench beneath them. Progress often works the same way: quiet effort becomes visible only after it has gathered enough strength.",
  "The first draft of an article is allowed to be awkward. Its purpose is to place an idea on the page so the writer can examine it honestly. A paragraph may change shape; a confident claim may become a question; an unnecessary flourish may disappear. Editing is not a punishment for writing badly. It is a second kind of thinking, one that asks the reader to follow without carrying extra weight. Read a sentence aloud and listen for the place where your attention slips. Then remove, rearrange, or clarify one small piece. Strong writing is usually discovered through several patient passes.",
  "At the edge of the city, a narrow footpath follows the river for almost five kilometers. The route passes warehouses, reeds, a small bridge, and a bench painted green by volunteers. On clear evenings, runners share the path with families and people walking dogs. No sign claims that the view is extraordinary, but the changing light makes every visit different. In March, the water carries branches from the hills; in July, it reflects long strips of orange sky. A familiar route can remain interesting when we stop expecting it to repeat yesterday and allow ordinary details to become new again.",
  "Learning a keyboard shortcut feels insignificant until the shortcut becomes part of a real workflow. At first, the fingers hesitate and the mind translates each instruction. After a week of deliberate repetition, the movement begins before the thought is complete. This is why small drills deserve respect. They are not separate from meaningful work; they are the quiet rehearsal that makes meaningful work smoother. Choose one action, practice it slowly, and notice where tension appears. Speed should be the result of confidence, not the goal that forces confidence to disappear.",
  "A local museum placed a blank card beside every exhibit and invited visitors to write one question. The questions were better than the curators expected. People wondered who carried a certain suitcase, why a painter used an unusual shade of green, and what happened to an unfinished machine. The cards changed the atmosphere from silent observation to shared curiosity. No visitor needed specialist vocabulary to participate. A question can be a form of welcome, especially when it makes room for uncertainty. The most valuable response is sometimes not an answer, but a more precise question.",
  "The baker arrived before sunrise because the first customers liked warm bread at 6:00. Her routine was exact, but never mechanical. She checked the humidity, adjusted the water, and watched the dough rather than trusting yesterday's measurements. On busy days, a delivery arrived late or an oven behaved strangely, so experience mattered more than a perfect schedule. By noon, the shelves were empty and the kitchen was quiet again. Craft depends on consistency, yet consistency does not mean repeating one motion without thought. It means noticing conditions and making the next good decision.",
  "A useful notebook is not a museum for perfect ideas. It is a workshop where incomplete thoughts can stand beside sketches, questions, and reminders. I keep one near the keyboard because a sentence often arrives while another task is underway. Writing it down prevents the mind from holding two jobs at once. Later, some notes look ordinary and a few seem impossible to understand. That is fine. The value is not in preserving every thought; it is in creating a dependable place where thoughts can wait until attention returns.",
  "The coastal town prepared for a storm by doing ordinary things carefully. Shop owners moved loose signs indoors, neighbors checked on older residents, and the library charged a dozen portable lamps. Nobody knew whether the wind would be severe, but preparation reduced the fear of being surprised. By evening, rain covered the streets and the power flickered twice. People shared updates without exaggeration, made tea, and waited. Calm is not the absence of risk. It is the result of knowing what can be done now, what must be watched, and what can safely wait until morning.",
  "A good conversation has a rhythm that is easy to miss when everyone is trying to sound impressive. One person speaks, another listens closely, and a thoughtful pause gives the next idea somewhere to land. The best questions do not turn the discussion into an interview; they show that the earlier words were heard. Even disagreement can be generous when it focuses on an idea rather than a person. Before answering, repeat the point in your own words. That simple habit prevents many arguments from growing around a misunderstanding.",
  "On the first day of a new job, the office seemed full of invisible rules. Which meeting room could be used? Where did people find the latest files? How much detail belonged in a status update? Instead of pretending to understand, Mira kept a small list and asked one question at a time. By Friday, the list had become a practical guide for the next newcomer. Confidence did not come from knowing everything immediately. It came from observing carefully, learning openly, and turning confusion into something another person could use.",
  "The city library extended its hours during exam season and placed a sign near the entrance: 'Quiet does not mean lonely.' Students arrived with laptops, pencils, snacks, and very different plans. Some worked for twenty minutes before taking a walk; others stayed until closing. The librarians did more than protect the silence. They helped people find reliable sources, explained the printer, and reminded everyone to rest their eyes. A shared environment can support concentration without demanding identical habits. Good spaces make focus easier while leaving people free to find their own method.",
  "A map is an argument about what deserves attention. It enlarges some roads, omits small turns, and chooses a symbol for every important place. When hikers lost the marked trail, they did not need a more beautiful map; they needed one that showed the stream crossing clearly. The lesson applies to plans, dashboards, and instructions. Information becomes useful when its shape matches the decision someone must make. Before adding another detail, ask what the reader will do with it. Clarity is not a shortage of information. It is information arranged with care.",
  "The musician practiced scales slowly enough to hear every uneven note. A visitor asked why she did not play the difficult piece instead. She explained that speed could hide a weak movement, while a slower tempo made the problem visible. After several minutes, the pattern became steadier, and the music sounded more relaxed. Improvement often feels less dramatic than performance because it happens below the surface. If a skill matters, practice the part that feels boring. Precision built in quiet moments is what makes difficult work appear effortless later.",
  "At 12:15, the small cafe filled with people escaping the rain. Coats dripped beside the door, umbrellas leaned against chairs, and the barista called names over the hiss of milk. A child drew a blue boat on a paper napkin while her father read the news. Nobody stayed for the atmosphere alone; they came for warmth, coffee, and a few minutes of shelter. Yet the ordinary scene felt generous. Places become memorable through repeated acts of attention: a clean table, a remembered order, or a smile offered when the day is inconvenient.",
  "A product is easier to use when its designer respects the user's next question. What happens after I click this? Can I undo it? Where did the saved file go? These questions are not signs of impatience; they are part of the experience. During a review, the team removed three decorative controls and added one sentence of guidance. The screen looked simpler, but the change was more than visual. It reduced hesitation. Good design does not show how much effort went into a product. It makes the important path feel natural.",
  "The hiking group started before dawn, carrying water, fruit, and a folded paper map. At the first viewpoint, the valley was hidden by fog, so someone suggested turning back. The guide waited ten minutes and watched the wind. Slowly, the gray layer opened, revealing fields, rooftops, and a silver road below. The view was worth the pause, but the larger lesson was about decisions. Patience is not always passive. Sometimes it means gathering one more piece of evidence before choosing a direction.",
  "A teacher asked the class to describe a paperclip without using the word 'metal.' The first answers focused on its shape, then its purpose, then the tiny friction that keeps pages together. The exercise seemed playful, but it revealed how quickly familiar labels stop us from noticing. When we describe something carefully, we see more of it. The same practice helps with problems at work. Replace a vague complaint with a specific observation, include an example, and ask what changed. Better language often creates the first workable solution.",
  "The repair shop kept a shelf of objects that customers had nearly thrown away: a clock with a tired spring, a lamp with a loose wire, and a radio that needed patience. The owner never promised that every item could be saved. He examined each one, explained the cost, and let people choose. Repair was slower than replacement, but it taught attention. A broken thing is not automatically worthless; sometimes it is simply asking for a different kind of care. That idea applies to tools, routines, and relationships too.",
  "In 2024, a small research team moved its weekly meeting from a crowded afternoon to 9:10 on Tuesday. The change sounded minor, yet the conversations became shorter and decisions became clearer. People arrived before the day's interruptions had multiplied. They prepared because the meeting had a reliable shape: a quick review, two questions, and a named next step. A schedule cannot solve every problem, but it can protect the conditions where good work happens. When a process feels heavy, change one assumption and observe what follows.",
  "The apartment balcony was only four meters wide, but it became a useful outdoor room. A folding chair fit beside a wooden planter, and a string of warm lights made the space inviting after sunset. On busy days, I used it for five minutes of air; on quiet days, I read there until the page blurred. The size did not matter as much as the invitation. A place becomes valuable when it makes a desired action easy to begin. Design the first step, and the habit has somewhere to live.",
  "A language changes when people use it, not when a dictionary tells them to stop. New words arrive through science, travel, music, and ordinary conversation. Some disappear; others become so familiar that their origins are forgotten. Reading widely helps a typist recognize patterns, punctuation, and tone without needing to analyze every sentence. It also makes practice less mechanical. A passage about a telescope feels different from one about a market, even when both require the same careful fingers. Variety keeps attention awake and makes fluency more flexible.",
  "The community radio station received a message from a farmer who wanted to thank the weather reporter. The forecast had warned of heavy frost, so he covered a young orchard before nightfall and saved the first blossoms. The reporter was surprised; the forecast had felt like routine work. Useful information often travels farther than its creator can see. This is why accuracy matters even when an audience is invisible. A careful sentence, a correct number, or a clearly typed instruction may quietly change what someone does next.",
  "When the office lost its internet connection, everyone discovered which tasks required a network and which only required concentration. People reviewed notes, cleaned their folders, and talked through decisions that had been postponed by endless messages. After two hours, the connection returned, but the room stayed quieter. Tools are valuable when they remove friction; they are not valuable when they become the only way to think. Build a process that can bend when circumstances change. Resilience is often just preparation combined with a calm alternative.",
  "The photographer visited the same market for six months, carrying the same small camera. At first, every image looked familiar: striped awnings, baskets of fruit, and scooters near the curb. Gradually, the repeated visits revealed change. A new sign appeared, a vendor began bringing flowers, and a boy who once hid behind his mother started carrying boxes. Attention deepens with return. The first visit collects impressions; the tenth begins to notice relationships. Practice works in the same way: repetition is not empty when perception keeps growing.",
  "An ambitious goal can become discouraging when it is written only as a final number. A runner changed her plan from 'finish a marathon' to 'walk or run for twenty minutes, four times this week.' The new target was smaller, measurable, and still connected to the larger dream. After a month, she had evidence that the habit was real. Numbers can motivate when they describe a behavior we can repeat, not when they judge a person we are still becoming. Make the next action visible, then let consistency create momentum.",
  "The museum's restored clock began running again at exactly 10:00, but the ceremony was delayed because a child had found a loose gear near the display. Instead of hiding the mistake, the curator invited everyone to watch the repair. She explained how the gear transferred motion and why a tiny misalignment stopped the whole mechanism. Visitors left with a better story than the original ceremony would have provided. Problems become less frightening when they are visible, named, and approached with care. Transparency is a practical form of trust.",
  "A long train journey gives the mind a different kind of workspace. The landscape changes without asking for a decision, and the steady motion creates a gentle boundary around attention. I read for a while, wrote a letter, and watched a flock of birds rise from a field. At 16:40, the train paused beside a station whose name I could not pronounce. Nothing remarkable happened, but the pause made the trip feel real. Useful rest is not wasted time; it is time that allows scattered thoughts to settle into a shape.",
  "The best teams do not avoid difficult feedback; they make it safe enough to use. A manager began each review by asking, 'What felt harder than it should have?' The question invited specific answers without assigning blame. One person described a confusing form, another mentioned a missing decision, and a third admitted that the deadline was unrealistic. The team changed the form, clarified ownership, and adjusted the schedule. Improvement began because honesty had somewhere to go. A culture is shaped by the questions leaders repeat.",
  "A careful typist does not stare at every key forever. The eyes learn to move ahead, the hands learn familiar distances, and attention returns to the sentence as a whole. This balance develops through practice that is challenging but not chaotic. Choose a passage with punctuation, numbers, and varied words; slow down when accuracy falls; and notice tension in the shoulders. Speed is useful only when it remains controllable. The goal is not to race a clock, but to make precise movement available when the work demands it.",
  "On Sunday evening, the neighborhood baker posted a handwritten note: 'Tomorrow's bread may be late; the oven needs one more repair.' Customers still arrived. Some bought pastries, some waited, and a few offered tools or advice. The delay became a small lesson in expectation. People are often more patient when they know what is happening and what can be done next. A clear message cannot remove every inconvenience, but it prevents uncertainty from adding a second problem. Communication is part of the work, not an extra after the work.",
  "A question mark changes the posture of a sentence. It asks the reader to pause, consider, and participate. A comma creates a smaller breath; a period gives an idea a clean edge. Punctuation is not decoration for a typist. It is a map of emphasis, timing, and meaning. When practice includes real prose, the fingers learn more than letter order. They learn how language moves. Read the passage once before typing, notice the pauses, and let the rhythm guide your hands without making them hurried.",
  "The final light in the studio came from a desk lamp beside a stack of sketches. The designer had spent three hours removing details from a poster, not adding them. Each deletion made the central message easier to find. At 21:05, she printed one last version and placed it beside the first. The two sheets looked surprisingly different, although the words were almost the same. Good work is often a process of protection: protect the main idea from noise, protect the reader from confusion, and protect your attention from needless motion."
];

const passageExtensions = [
  "Before the day ended, I noticed that the plan had changed in three small ways, yet its purpose was still intact. That is a useful measure of discipline: not refusing to adapt, but adapting without losing the reason you began. Type the sentence slowly, including every comma, apostrophe, and full stop. Accuracy gives speed a reliable place to grow.",
  "The workshop became valuable because everyone could contribute something practical. One person brought a screwdriver, another brought a story, and someone else simply made room at the table. By 17:00, the repaired objects were less important than the confidence people carried home. Shared effort turns a task into a memory, and a memory is easier to return to.",
  "Later, the team wrote its decisions in plain language and sent them to everyone involved. A short record prevented the same debate from returning the following week. Good systems preserve attention for new problems instead of making people rediscover old answers. When a process becomes clear, people can spend more energy on judgment, creativity, and care.",
  "The gardener kept a small journal with dates, temperatures, and observations that seemed unimportant at first. Months later, those notes explained why one bed flourished while another struggled. Evidence does not need to be complicated to be useful. A patient record can turn a vague impression into a pattern, and a pattern can guide the next season.",
  "After the revision, the article sounded less like a performance and more like a conversation with a thoughtful reader. The writer kept the difficult idea but gave it a simpler entrance. This is a kindness worth practicing in every form of communication. Make the path easy to enter, then trust the reader enough to continue.",
  "The path also taught the walkers to measure distance by landmarks rather than by impatience. A bridge meant one kilometer; the red bench meant another. Visible milestones made the whole route feel possible. Large goals become friendlier when progress has places to pause, look around, and recognize that the starting point is no longer nearby.",
  "A shortcut should remove effort, not remove understanding. The typist still needs to know what action is happening and when it is safe to use it. Good fluency combines memory with awareness. Try the movement, notice the result, and adjust your hands before adding another shortcut. A small, dependable improvement is better than a collection of uncertain tricks.",
  "Visitors returned the next month with questions shaped by the first visit. One asked about materials; another asked who had been excluded from the official story. Curiosity grows when it receives respect rather than a rushed answer. Leave a little space after each explanation. Someone may be preparing the question that changes the whole room.",
  "The baker measured carefully, but she also trusted signals that no recipe could list completely. Dough has a texture, a smell, and a kind of resistance that experienced hands recognize. Practice builds this quiet vocabulary. It teaches us to combine instructions with observation, so the next decision is informed by both a rule and the world in front of us.",
  "Weeks later, the notebook contained a useful trail through several projects. A crossed-out phrase showed where an idea had changed; a star showed where two unrelated thoughts had met. The page did not need to be beautiful to be valuable. It only needed to be honest enough that the future reader could understand what the earlier mind was trying to solve.",
  "The town's preparation did not make the storm smaller, but it made the response calmer. After the clouds cleared, people returned borrowed lamps, swept leaves from doorways, and compared what they had learned. Readiness is improved by reflection. Ask what worked, what failed, and what should be changed before the next uncertain day arrives.",
  "The conversation ended with no dramatic agreement, yet both people understood the disagreement more accurately. That was progress. A useful exchange does not always produce the same opinion; sometimes it produces a fairer description of the difference. Listen for the sentence beneath the sentence, and answer the idea that was actually offered rather than the one you expected.",
  "Mira eventually wrote a one-page guide and placed it beside the shared printer. The next newcomer needed fewer questions, while Mira gained time to learn a more advanced part of the job. Teaching is not only generosity; it is a way to make knowledge durable. Explain a process clearly enough that another person can carry it forward.",
  "One student preferred complete silence, while another worked best with quiet instrumental music. The library supported both without pretending that one method was universal. Good environments offer structure without demanding sameness. Notice the conditions that help you focus, then design them deliberately instead of waiting for concentration to appear by accident.",
  "A map becomes trustworthy when it admits what it does not show. The hikers marked the washed-out trail and added a note about the difficult crossing, helping the next group make an informed choice. Honest limits are useful information. Say what is known, identify what is uncertain, and let the person using the map decide with open eyes.",
  "The musician recorded the practice session and listened the next morning. A hesitation she had not noticed while playing was obvious in the recording, but so was the improvement after ten careful repetitions. Feedback works best when it is close enough to guide action and gentle enough to invite another attempt. Observe, adjust, and repeat without turning the process into punishment.",
  "By closing time, the cafe floor was wet with footprints, but the staff had kept the room welcoming. Small gestures accumulated: a towel by the door, a dry chair, a warm refill. Hospitality is often made from details that nobody mentions afterward. The same is true of good tools; their best decisions are felt as ease rather than praised as features.",
  "During the review, one designer asked whether the new control solved a real problem or merely displayed an available option. The question removed a week of unnecessary work. A feature should earn its place by helping someone complete a task. If its purpose cannot be explained simply, pause before adding it. Restraint is a form of respect for attention.",
  "The guide kept the group moving only when the trail was clear. At uncertain turns, he stopped, checked the map, and invited another person to look. Leadership did not mean being the fastest walker. It meant protecting the group's ability to make a sound decision. A calm pause can be more useful than confident motion in the wrong direction.",
  "The class continued the exercise with objects on their desks: a pencil, a cup, and a folded receipt. Each description became more precise when the familiar label was removed. Attention expands when language becomes specific. Try replacing 'it is confusing' with the exact moment confusion begins. Precision gives a problem an edge that can be held.",
  "The owner kept every repair record, including the jobs that were not worth the cost. Those entries helped him explain future choices honestly and avoid repeating an expensive mistake. Failure becomes useful when it leaves behind information rather than shame. Keep the lesson, change the method, and let the next attempt begin with better evidence.",
  "The team's new schedule did not create more hours; it protected one hour from being fragmented. In that space, people could think through a problem without switching between alerts and unrelated requests. Focus is partly a decision about what not to invite. Guard a small block of attention, and use it for the work that benefits most from continuity.",
  "The balcony's chair was not comfortable enough for an entire afternoon, but it was comfortable enough to begin. That distinction mattered. Habits often need an inviting doorway rather than a perfect environment. Make the first version easy, use it honestly, and improve it after learning what the routine actually requires.",
  "A passage with varied punctuation asks the hands to listen as well as move. The comma is a small turn, the quotation mark opens another voice, and the number 42 interrupts a familiar pattern. These changes keep practice realistic. Fluency is not memorizing one road; it is staying composed when the road changes beneath you.",
  "The message from the farmer reminded the reporter that careful work can matter far beyond its original setting. Nobody had asked for applause, but the story strengthened the station's commitment to clear forecasts. Results are not always visible at the moment of effort. Continue doing the accurate thing, even when the person helped by it remains unknown.",
  "When the connection returned, the team kept its paper notes because they had revealed a simpler process. Technology was welcomed back, but it no longer carried every responsibility. A resilient workflow uses tools deliberately and keeps a human understanding of the underlying task. Know what the system does, and know what you would do if it disappeared.",
  "The photographer's final collection included no single perfect visit. Its strength came from accumulated observation, from returning when the weather changed and when the market was quiet. Repetition becomes meaningful when each attempt has a slightly different question. Enter practice with curiosity, not merely with a demand to produce the same result faster.",
  "The runner marked each completed session with a small dot on the calendar. The pattern grew slowly, then became impossible to ignore. A visible chain does not create discipline by itself, but it makes consistency easier to remember. Measure actions you control, celebrate honest repetition, and let the larger result remain a consequence rather than a daily threat.",
  "The curator left the repaired gear visible beside the clock, with a note explaining what had been adjusted. Visitors could understand both the beauty of the mechanism and the care required to keep it working. Finished work is more trustworthy when its maintenance is not hidden. Build for use, explain the important parts, and leave room for future hands.",
  "At the next station, I wrote down the thought that had formed during the pause. It was not a finished plan, only a possible beginning. Rest had done its quiet work by separating the useful idea from the noise around it. Return to important questions after a pause; distance often reveals which details deserve another look.",
  "The manager ended each review by asking what support would make the next attempt easier. Sometimes the answer was training; sometimes it was a clearer deadline or a missing decision. Improvement is practical when it changes conditions, not only when it asks people to try harder. Give effort a fair environment, then expect thoughtful work.",
  "The typist eventually stopped watching the clock and began listening to the sentence. Her speed rose because her attention was no longer divided between panic and movement. A timer is useful feedback, but it is not the author of the work. Stay with the next character, protect accuracy, and allow a reliable rhythm to become visible.",
  "The baker's note remained on the door after the oven was repaired, because the customers had appreciated the honesty. A small delay had become a reminder that trust is built in ordinary moments. Say what is happening, explain the next step, and keep the promise that remains possible. Clear communication turns inconvenience into cooperation."
];

const sharedPracticeTail = "Keep your eyes a few words ahead, let the punctuation shape the rhythm, and do not chase a number that makes your hands tense. If an error appears, recover calmly and continue from the next character. A useful session is not defined by perfect typing; it is defined by honest attention, steady correction, and the willingness to try again tomorrow. Return to the keyboard with curiosity.";

export const passages = passageDrafts.map((passage, index) => `${passage} ${passageExtensions[index]} ${sharedPracticeTail}`);

export const ranks = [
  { name: "Baby Bunny", minWpm: 0, description: "Every fast typist starts somewhere. Keep hopping!" },
  { name: "Kitten", minWpm: 11, description: "Soft and steady! Your fingers are finding their rhythm." },
  { name: "Puppy", minWpm: 21, description: "Good job! Your typing skills are growing every day." },
  { name: "Bumblebee", minWpm: 31, description: "Clever and quick! You're getting comfortable with the keyboard." },
  { name: "Panda", minWpm: 41, description: "Calm, focused, and getting faster with every test." },
  { name: "Unicorn", minWpm: 51, description: "Small but speedy! Your typing rhythm is getting stronger." },
  { name: "Cheatah", minWpm: 61, description: "Magical speed! Your fingers are flying across the keyboard." },
  { name: "Phoenix", minWpm: 71, description: "You're rising fast! Your typing is becoming seriously impressive." },
  { name: "Dragon", minWpm: 81, description: "Powerful typing! Your keyboard skills are blazing." },
  { name: "Pegasus", minWpm: 91, description: "You're flying now! Your typing speed is truly impressive." },
  { name: "Comet", minWpm: 101, description: "Lightning fast! You're leaving ordinary typing speeds behind." },
  { name: "Galaxy", minWpm: 111, description: "Out-of-this-world speed! Your keyboard control is incredible." },
  { name: "Legend", minWpm: 121, description: "A legendary typist! Your command of the keyboard is exceptional." },
  { name: "Mythic", minWpm: 140, description: "Beyond ordinary speed. You've reached mythical typing status." }
];

export function getRank(wpm) {
  return [...ranks].reverse().find(rank => wpm >= rank.minWpm) || ranks[0];
}
